import Head from 'next/head'
import React, { FC } from 'react'
import Header from '../components/Header'
import TrackPlayer from '../components/TrackPlayer'

interface IMainLayoutProps {
    title: string;
}

const MainLayout: FC<IMainLayoutProps> = ({ children, title }) => {
    return (
        <>
            <Head>
                <title>Music Player | {title}</title>
                <meta name="description" content="Generated by create next app" />
                {/* <link rel="icon" href="/favicon.ico" /> */}
            </Head>
            <Header/>
            <div style={{paddingBottom: 100}} >
                { children }
            </div>
            <TrackPlayer/>
        </>
    )
}

export default MainLayout
